### ISSUE TITLE
close PRs from 2018 or earlier

### ISSUE THREAD

**Issue by beckermr** [conda-forge/staged-recipes#10168]
We have PRs from 2018 or earlier still open. We are still debating the CFEP on automated tooling, but I think we can all agree that issues more than 10 months old are eligible for closure.

@conda-forge/staged-recipes what do you think?

**Comment by mbargull** [comment]
I'd be in favor, however IMHO best with a "friendly" accompanying message à la "Thanks for your PR ... closing since it has not been updated ... feel free to reopen or issue a new PR if you are still interested ..."
to avoid discouragement.

If no one from @conda-forge/core or @conda-forge/staged-recipes is opposed and we have a copy-paste-able message ready, I'll happily sit down tomorrow morning with a good tea and take over a batch ;).

**Comment by beckermr** [comment]
I have made a CFEP to enable a bot to do this. https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/18

I will call for a vote soonish I think.

**Comment by beckermr** [comment]
@CJ-Wright suggested the github stale bot which seems like it does exactly what we need

**Comment by beckermr** [comment]
I agree on a very friendly message per the CFEP!

**Comment by mbargull** [comment]
Yep, I saw the CFEP. I was just suggesting we could begin it with some "manual labor" for now.
I definitely prefer some kind of automation, but CFEPs tend to take time until they are in place...

**Comment by beckermr** [comment]
Ahhhhh ok. Well I think this one is simple enough that it will pass without an issue (I hope anyways.). If it does not, I don't think doing it manually is in good faith to the CFEP process, but might be acceptable.

I will call for a vote now and we can see what happens!

**Comment by mbargull** [comment]
We should also add a label to those PRs. That'd make handling/categorizing easier. I think `inactive` would be very appropriate.
We can then:
1. Add the `inactive` label.
2. Add a comment with the message.
3. Close the PR.

Steps 1. & 2. can happen at the same time and 3. could be done after some amount of time, e.g., some days or a week. The message can then be adjusted to say "we will be closing" instead of "we are closing". Maybe this would be even better received since we give an interim in which the contributor can react?

**Comment by beckermr** [comment]
The stale bot does all of this. It adds a label and leaves a message. Then some amount of time later, it closes the PR.

**Comment by mbargull** [comment]
Perfect!

**Comment by mbargull** [comment]
Can you draft a copy-paste-able
> "friendly" accompanying message à la "Thanks for your PR ... closing since it has not been updated ... feel free to reopen or issue a new PR if you are still interested ..."

for the "we will be closing"  and/or "we are closing" case?

**Comment by beckermr** [comment]
Here you go!

will close (sent after 5 months):

> Hi friend! We really, really, really appreciate that you have taken the time to make a PR/issue on `conda-forge/staged-recipes`! `conda-forge` only exists because people like you donate their time to build and maintain `conda` recipes for use by the community. In an effort to maintain this repository and increase the signal-to-noise for open PRs/issues, the maintainers of `staged-recipes` close excessively old PRs/issues after six months. This PR/issue will remain open for another month, and then will be closed. If you'd like to keep it open, please comment and we will be happy to oblige! Cheers and thank you for contributing to this community effort!

closing (sent one month after the above):

> Hi again! About a month ago, we commented on this PR/issue saying it would be closed in another month if it was still inactive. It has been a month and so now it is being closed. Thank you so much for making it in the first place and contributing to the community project that is `conda-forge`. If you'd like to reopen this issue, please feel free to do so at any time! Cheers and have a great day!

**Comment by beckermr** [comment]
So CFEP-11 just passed, meaning we are free to add the stale bot to this repo!

**Comment by beckermr** [comment]
link for reference https://github.com/conda-forge/cfep/blob/master/cfep-11.md

**Comment by beckermr** [comment]
I submitted a request to do this. @conda-forge/core will need to accept. Then we put in a PR with the config.

**Comment by beckermr** [comment]
see the config here: https://github.com/apps/stale

**Comment by isuruf** [comment]
stale is now installed. Can you send a PR for the config?

**Comment by beckermr** [comment]
Yup working on it now!

**Comment by beckermr** [comment]
See https://github.com/conda-forge/staged-recipes/pull/10672
