### ISSUE TITLE
Patch and add virtualenv

### ISSUE THREAD

**Issue by kalefranz** [conda-forge/staged-recipes#1139]
Python's virtualenv has always been problematic with conda.  A detailed explanation of what usually happens is here: https://github.com/conda/conda/issues/1367#issuecomment-195596461

> Let's say I have conda installed at `/conda` and so my python executable indicated by `which python` is at `/conda/bin/python`.  That means the shared library that python runs against at startup/load time is `/conda/lib/libpython2.7.dylib`.  Actually, it links against `../lib/libpython2.7.dylib`.  That is, the link path is relative.
> 
> Say I delete that file though... The OS X system loader has a library search path similar to the executable path `PATH`. By default on OS X, this library search path is `$HOME/lib:/usr/local/lib:/lib:/usr/lib` (see `man dyld`). So, when I delete `/conda/lib/libpython2.7.dylib`, then when `/conda/bin/python` runs, the loader will end up finding a `libpython2.7.dylib` at `/usr/lib/libpython2.7.dylib`.  The problem is, that library is compiled for the _system_ python at `/usr/bin/python`, and thus we get that symbol error.
> 
> Now let's look at virtualenv.  Say I'm working on myproject located at `~/projects/myproject`, and in that directoryI create a virtualenv with `virtualenv ve --python=/conda/bin/python2.7`. Now after `source ~/projects/myproject/ve/bin/activate`, `which python` shows `~/projects/myproject/ve/bin/python`. What dynamic library is that python going to load against? Well, it would be `../lib/libpython2.7.dylib` or `~/projects/myproject/ve/lib/libpython2.7.dylib`. Except that file doesn't exist. (In fact, `~/projects/myproject/ve/lib/` will probably be completely empty.)  So the loader falls back to the library search path and finds `/usr/lib/libpython2.7.dylib`.
> 
> :boom: Symbol error.

Later in that thread, @stuarteberg suggested a workaround hack https://github.com/conda/conda/issues/1367#issuecomment-217958169.

> It turns out you can _pre-emptively_ create the virtual environment (as an empty directory), and then symlink the missing file _before_ running `virtualenv` (`libpython2.7.dylib`).  Then `virtualenv` works as expected.
> 
> In other words:
> 
> ``` bash
> $ mkdir -p ve/lib
> $ cd ve/lib && ln -s /path/to/miniconda/lib/libpython2.7.dylib && cd -
> $ virtualenv ve
> ```

**Bottom line:** I would love the community's help to build virtualenv as a conda package, but patch the source code itself to work "as expected."

If someone wants to start digging in, the entry point I'd suggest would be looking closely at the `install_python` function https://github.com/pypa/virtualenv/blob/4b707b87d43e7e0a945ad831e6ce483b45440149/virtualenv.py#L1089

**Comment by kalefranz** [comment]
Cross-linking: http://stackoverflow.com/questions/38594047/error-running-tests-with-conda-and-tox/38731951

**Comment by kalefranz** [comment]
Also related: https://bitbucket.org/hpk42/tox/issues/273/support-conda-envs-when-using-miniconda

**Comment by jakirkham** [comment]
Would be curious to hear from @hayd on this given he wrote [`ctox`]( https://github.com/hayd/ctox ).

**Comment by hayd** [comment]
From my point of view, I got ctox working pretty well for my usecases (I should probably remove some of the extensive warnings on the README). Namely, pdb into a failing env.

The problem with ctox is that it's doesn't try and be clever about resolving dependencies: if you have many dependencies *and* they are changed frequently, it is going to be quite slow... since it starts from scratch if the dependencies changed. Anything which makes the following operation easier/faster in conda itself would be fantastically helpful:

Compare a list of OLD_DEPS against NEW_DEPS (aka the INSTALL_REQUIRES), so if the following operation was cheap in conda that would make things a lot easier:
- Had OLD_DEPS is  A, D, F, H.
- The environment has conda packages A (with dependencies B, C), and D (dep. C, E) and pip packages F (dep. G), H (dep. G, I) i.e. all A, B, C, D, E, F, G, H, I are installed, some via conda, some via pip.
- If NEW_DEPS is A, F.
- I want to update the env to A, B, C, F, G (as only deps required are still required, and those no longer requires *must* be removed).

Perhaps there's already a neat way to do this? :)
Even better if you can compare NEW_DEPS against the environment (without needing OLD_DEPS), that way if the env has been "messed with" it'll be reset.

I found this pretty hard to reason about when I wrote ctox, so I didn't - I just started afresh (my deps rarely change anyway, so naive caching worked fine). There also an issue since there is (or was?) no conda -> pip fall-through, so I had to work around that.

In ctox the conda env is `package_dir/.tox/{envname}/bin/python`.

Just adding a ctox wrapper/cli to build whichever ctox env and calling `source activate {envname}` might get you much of the way there...

**Comment by mingwandroid** [comment]
Fixed now. It conda's virtualenv package if you need it.

**Comment by jakirkham** [comment]
It also got added as a feedstock in conda-forge too.
