### ISSUE TITLE
wiki page for depending on C/C++ build system

### ISSUE THREAD

**Issue by croth1** [conda-forge/staged-recipes#1193]
Would it be possible to add a wiki page that explains current conventions on how to depend on the toolchain/compilers for C/C++? 

Different projects have different solutions and as they are (hopefully) converging to a common standard, it would be nice to have a quick reference to see how it should be done in conda-forge.

**Comment by jakirkham** [comment]
We created the `toolchain` package to try and standardize this. In most cases, one can simply add it as a `build` dependency and it will just work. There are some funny cases with `libtool`. We have discussed several options to address that, but have not come to a consensus.

There are a few challenging build cases where the `toolchain` is not sufficient. Namely this is due to bad behavior by `libtool`. Though there may be some other strange cases that deserve further inspection. Due to some of these challenging cases, we have had some trouble coming to a consensus about how to standardize builds. It has been added as a topic on our agenda.

On OS X we have used `clang`/`libc++` primarily, but have a few troublesome packages that need to be switched over. Though our long term goal is to get a `gcc` package that we can build OS X and Linux packages with. As for Linux, we have been using devtoolset-2 primarily.

The Fortran situation is a bit challenging ATM. Initially we used the `gcc` package and simply shipped `libgcc`. However, we have found this a bit troublesome as things tend to pick up on the `libgcc` libraries during a build and not the system ones. As a result, we get a mix of system linked libraries and `libgcc` linked libraries. There are a few cases where we have explored shipping a `libgfortran` library only. However, this is very far from standardized and is still a bit mess ATM.
