### ISSUE TITLE
Package dgl

### ISSUE THREAD

**Issue by hadim** [conda-forge/staged-recipes#12537]
I am considering packaging [dgl](https://github.com/dmlc/dgl) into conda-forge but I don't know whether this is something possible.

See https://github.com/dmlc/dgl/issues/1855 for context.

They already have a conda channel at https://anaconda.org/dglteam

dgl is built against different versions of CUDA, see https://github.com/dmlc/dgl#using-anaconda and they provide different packages per CUDA version which I believe is not the best way to do it. I think it makes more sense to have a single package with different variants that are selected according to the presence or not of a specific cudatoolkit in the graph of deps. Please correct me if I am wrong (it seems to be similar to what pytorch is doing on their own channel).

Do you have an example of such packages in conda-forge I could start with to build dgl?

ping @conda-forge/staged-recipes

**Comment by hadim** [comment]
Closing here in favor of https://github.com/conda-forge/staged-recipes/pull/12552 and https://github.com/dmlc/dgl/issues/1855

**Comment by jakirkham** [comment]
Reopening since this appears not to have been completed

**Comment by jakirkham** [comment]
There's a more recent attempt in PR ( https://github.com/conda-forge/staged-recipes/pull/18620 ), which has since been superseded by PR ( https://github.com/conda-forge/staged-recipes/pull/22691 )

**Comment by mikemhenry** [comment]
Haha yes there are a trail of PRs for this project! Thank you @jakirkham for helping this along! 

Really the slow part is doing this the right way :tm: since in https://github.com/conda-forge/staged-recipes/pull/18620 we showed we can get it to build, but had some issues with vendored packages. @hmacdope is now working on trying to un-vendor as much as we can... 

I don't want trying to get this perfect to prevent us from getting this moved to a feedstock. We have improved things considerably re: modifcations to `dgl` build process to use system packages instead of vendoring everything.

**Comment by jakirkham** [comment]
Yeah that seems pretty reasonable

Devendoring can help with cutting down build time and avoiding clobbering

Though yeah sometimes these issues need further iteration in the feedstock

**Comment by mikemhenry** [comment]
Yeah I found in particular that getting CUDA stuff working tends to go easier in the feedstock. And I would like to play with that once we get it in a feedstock to work with the new cuda12 packaging 

Thanks!

**Comment by jakirkham** [comment]
Would be happy to work with you on CUDA 12 builds once we get there 🙂
