### ISSUE TITLE
How to add package that are in bioconda in the recipe?

### ISSUE THREAD

**Issue by rbeucher** [conda-forge/staged-recipes#12952]
I am working on a recipe that needs a package that exist in Bioconda but not in conda-forge. How can add it to the recipe?

Thanks!

**Comment by cpauvert** [comment]
Hi @rbeucher 
From what I understood and experienced (not in `bioconda` but in the `r` channel) you have to submit a recipe for the package that you depend on. Try perhaps to contact the maintainer of the package if they can assist in submitting the recipe.
Best,

**Comment by jakirkham** [comment]
cc @conda-forge/bioconda-recipes

**Comment by mfansler** [comment]
Technically, one can add the `bioconda` channel to the `channel_sources`, e.g.,

**conda_build_config.yaml**
```yaml
channel_sources:
  - conda-forge,bioconda,defaults
```

and then put the dependency in the `meta.yaml` where it is needed.

However, the two questions that come up are:
- Should your package be on Bioconda instead of Conda Forge?
- Is the dependency so general that it should be on Conda Forge rather than Bioconda?

**Comment by rbeucher** [comment]
Thanks for that.
