### ISSUE TITLE
Package naming convention

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/staged-recipes#1559]
Since that the number of package in conda-forge grows quickly, I was wondering if you discussed the conda package naming convention.

For example, I was going to propose a recipe for `gtest`. The debian source package name for it would be libgtest (although at the moment, there is only the source package libgtest-dev)

Should conda or conda-forge try to enforce similar conventions?
- `numpy` - > `python-numpy` and `pandas -> python-pandas` (just being somewhat provocative here)
- `gtest` -> `libgtest`.

**Comment by jakirkham** [comment]
We have and we have changed our minds more times than we probably should. See this [adventure]( https://github.com/conda-forge/conda-forge.github.io/issues/18 ). 😄

Yeah, we went through a `python-` phase and end up backing it out almost entirely because it resulted in clashes with `defaults` (which we are still dependent on) and caused a range of surprising issues for users. There is also the feeling we don't want to break the PyPI name expectations that one would have when using a `requirements.txt` file with `conda`.

Sometimes we use `lib`, but more for disambiguation, but I don't think anyone likes using it out of the gate.

Long term I don't think prefixing is going to be a thing. We will move towards namespacing as generally outlined in this [gist]( https://gist.github.com/mcg1969/da5aec380d2ed083b79ddcf151ca16f1 ).

As for Google Test's name, please see this [comment]( https://github.com/conda-forge/staged-recipes/pull/1564#issuecomment-247366620 ).

**Comment by patricksnape** [comment]
Yeah I prefer the namespacing option over prefixing. I would vote for `gtest` in this case.

**Comment by jakirkham** [comment]
cc @mcg1969

**Comment by mcg1969** [comment]
SIGH. I know. We need to get this done.

**Comment by jakirkham** [comment]
No worries. That was not so much a nudge as an "oops, 😳 forgot to copy Michael".

**Comment by mcg1969** [comment]
And someone asked me about the graphviz debacle today, too

**Comment by jakirkham** [comment]
Yeah, the developer did us no favors there when choosing that name. FWIW I did add `python-graphviz` a little while back. Feel free to advise them to install that.

**Comment by jakirkham** [comment]
Going to bravely say we have *resolved* this issue. While there are discussions about how to better handle package naming and different language implementations or bindings, these have largely moved to other places and are more up-to-date/better followed there. So will close this out.

**Comment by jklaise** [comment]
@jakirkham what is the current status of this and implementing namespaces? Finding your last comment quite cryptic, where are these discussions happening?
