### ISSUE TITLE
Save CI time by using nomkl

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/staged-recipes#197]
Could we save some CI time by using `nomkl`? What would be the consequences?

**Comment by jakirkham** [comment]
Here are the consequences:

1. Linux will use OpenBLAS (provided by Continuum).
2. Mac will use the Accelerate Framework (system provided).
3. Windows won't work (no other option besides MKL at present).

There were discussions about using OpenBLAS as a fallback for Windows ( https://github.com/conda/conda-recipes/pull/586 ), but AFAIK nothing has been done on this front.

Accelerate on Mac can be tricky because it is not fork-safe. Meaning using things like multiprocessing (e.g. with scikit-learn), will cause the program to crash. I believe this is a segfault, but don't recall the exact ATM. This turns out to be quite tricky to diagnose.

Linux using OpenBLAS is fine for the most part. However, `libgfortran` is shipped with it as OpenBLAS is dynamically linked to it. This may not be the gfortran that users expect to use (i.e. with applications they have already linked), which can cause problems.

Though your point about not always using `mkl` is well taken. I think it may be best to consider bundling up our BLAS at present (probably OpenBLAS) and using that if we can. That way we can guarantee all systems have it and it will be useful for our packaging as well. Here are my [thoughts]( https://github.com/conda-forge/staged-recipes/issues/80#issuecomment-197394277 ) on this at present.

**Comment by ocefpaf** [comment]
Thanks @jakirkham. Closing this.
