### ISSUE TITLE
Use a "template" branch, to not have to clone 100k revisions

### ISSUE THREAD

**Issue by kno10** [conda-forge/staged-recipes#21137]
### General comment:

To add a new recipe, one has to clone the "main" branch, which has 100k revisions by now; the resulting git checkout has some 87 MB of which only ~40k are actually in the current revision, while most of the history consists of adding and removing packages immediately again.
Why not use a "template" branch for new submissions, and merge them into a "staging" branch or similar?

Sorry if this is a recurring request, I did not find it in the issues list yet.

**Comment by chrisburr** [comment]
The simplest way to avoid the history of staged recipes is to use shallow clones instead, i.e.

```bash
git clone git@github.com:$GITHUB_NAME/staged-recipes.git --depth 1
```

(This downloads ~40KB instead of the full ~87MB.)

>  Why not use a "template" branch for new submissions, and merge them into a "staging" branch or similar?

I think this wouldn't work very well in practice as people would have to know to change the base branch when they create the pull request (which likely means most pull requests will need to be fixed by staged-recipes maintainers). Alternatively they'd have to know to clone the template branch instead and adjust their git command accordingly (at which point you can use shallow clones).

**Comment by kno10** [comment]
Ok, granted now that I got a step further in the packaging: the 87 MB likely do not matter much when you easily end up getting some 20+GB just to dry-run the build with docker... I must say, building for pypi with Github actions so far was a _lot_ easier than getting the conda build to work.
