### ISSUE TITLE
Cannot install sklearn-genetic-opt from conda-forge into Python 3.11 environment even with all dependencies met

### ISSUE THREAD

**Issue by RNarayan73** [conda-forge/staged-recipes#24079]
### Bug:

**System information**
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11 Pro
Sklearn-genetic-opt  version: 0.10.1
Scikit-learn version: 1.3.0
Python version: 3.11.4
deap version: 1.4.1
numpy version: 1.24.3
tqdm version: 4.65.0

**Describe the bug**
Despite dependencies satisfied for deap, scikit-learn, numpy, the following error occurs:

> Collecting package metadata (current_repodata.json): done
> Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: |
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versions
> 
> Package python conflicts for:
> python=3.11
> sklearn-genetic-opt -> python[version='>=3.8']
> sklearn-genetic-opt -> deap[version='>=1.3.3'] -> python[version='3.10.*|3.9.*|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.6|3.8.*|3.7.*|3.6.*|>=2.7|>=3.7']
> 

**To Reproduce**
1. Run `conda create -n test python=3.11 sklearn-genetic-opt -d`

**Expected behavior**
No error should occur when installing from conda-forge into a Python 3.11 environment

**Screenshots**
N/A

**Additional context**
However, installing through pip from pypi works fine

**Comment by bollwyvl** [comment]
Using the `mamba` solver, this is a little clearer:

```
$ conda lock --mamba --kind=explicit --platform win-64 --file environment.yml 
Locking dependencies for ['win-64']...
INFO:conda_lock.conda_solver:win-64 using specs ['deap', 'scikit-learn', 'numpy', 'python 3.11.*', 'sklearn-genetic-opt']
Failed to parse json, Expecting value: line 1 column 1 (char 0)
Could not lock the environment for platform win-64
Could not solve for environment specs
The following package could not be installed
└─ sklearn-genetic-opt   is uninstallable because it requires
   └─ tensorflow >=2.0.0 , which does not exist (perhaps a missing channel).
```

This is likely due to `sklearn-genetic-opt` having a dependency on `tensorflow 2`, which is not available for windows from `conda-forge` at this time. "Just build it for Windows" in this case is untenable, as it takes longer to build than the donated CI provides. This is also a dependency where "just get it from some other channel," may also not work.

The following issue suggests some approaches that could help unstick this particular issue:

- https://github.com/conda-forge/sklearn-genetic-opt-feedstock/issues/1

However, this is unlikely to be solved on this repository.
