### ISSUE TITLE
Add libgpuarray

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#2411]
For theano, we need a package of `libgpuarray`. So it would be great if we can figure out what we need to do to add it.

xref: https://github.com/conda-forge/staged-recipes/pull/574#issuecomment-234598916

cc @abergeron @nouiz

**Comment by jakirkham** [comment]
xref: https://github.com/conda-forge/theano-feedstock/issues/7

**Comment by abergeron** [comment]
If you do it with the recent versions (like 0.6.0), this should be easy since it only need cmake and a C compiler.  All the gpu stuff (cuda, cublas, opencl, clblas, ...) is loaded dynamically at runtime and it doesn't need to be present on the build machine.

I can get the recipe from the anaconda guys as a basis for the one on conda-forge if that would help.

**Comment by abergeron** [comment]
I've just made #2457

**Comment by jakirkham** [comment]
Thanks @abergeron. Will be sure to take a look.
