### ISSUE TITLE
Print the rate limit of conda-forge-admin instead of conda-forge-manager

### ISSUE THREAD

**Issue by isuruf** [conda-forge/staged-recipes#2919]
Since we are hitting rate limit of conda-forge-admin, we should print the rate limit of it to see what's going on.

**Comment by isuruf** [comment]
@conda-forge/core can you create a new github token for `conda-forge-admin` and put it here, https://github.com/conda-forge/staged-recipes/blob/master/.travis.yml#L15 as `GH_TOKEN2` ?

**Comment by jakirkham** [comment]
Unfortunately that won't work. The user itself is hitting the rate limit. Regardless of how many tokens we add for that user, the rate limiting will still be applied to that user.

The reason we are hitting the rate limit is because AppVeyor is using our one `conda-forge-admin` bot to start all builds in our org instead of applying this to individual users opening PRs. Have tried to separate that bot from anything else that is not connected to AppVeyor to mitigate the issue. As we don't have this issue with other CIs (probably as other CIs are applying usage against individual user's as opposed to a bot), I think that AppVeyor can fix this issue. Had raised issue with them ( https://github.com/appveyor/ci/issues/1002 ) to try and get this addressed. However have not had much luck explaining this to them it seems. Maybe someone else can help them understand the steps required to fix this issue.

**Comment by isuruf** [comment]
Yes, I know. I think printing the rate limit for `conda-forge-admin` would still be useful, just to confirm the issue here.

**Comment by isuruf** [comment]
How about creating a new user? This won't help with the existing packages, but if appveyor is using the token of the bot, using a new token will help with new packages.

**Comment by jakirkham** [comment]
So then the new feedstocks will be connected to the new bot. While this could work temporarily until that bot runs up against the limit, this introduces some other challenges.

First what if we need to determine which bot is associated with which feedstocks' AppVeyor accounts? The only way we have known up until now is that only one bot has been used with AppVeyor. If that changes, we have no way to know which bot is in use.

Second bots are IMHO poorly managed now. Admins can create and setup a bot if they need them. However there is no safe established way of sharing the credentials of the bots. This causes issues if a bot has problems and the admin who created the bot cannot be reached (as has happened before). Admittedly this is more of an argument for getting organized than anything, but it is also an argument against growing the bot fold until we determine how to do so.

Third this is really only a stopgap that ultimately needs to be addressed by more and more bots. When we had run into another problem like this and went to GitHub for a rate limit increase, they responded by saying that this wouldn't really permanently solve our problem and that we should try to use our users tokens to get the throughput needed. While that didn't really apply to that problem, I can't disagree with GitHub's logic and think it definitely applies here with AppVeyor.

We should be scaling by users not bots. This is really on AppVeyor to handle somehow and we should really be approaching them with this problem.

**Comment by jakirkham** [comment]
FWIW I think part of the reason this is getting so bad is we are adding a bunch of feedstocks that need to be added on AppVeyor and then built on it. This is in addition to the normal load that AppVeyor experiences. That said, we should still push for a solution from AppVeyor as this will only become more noticeable as we grow.

**Comment by isuruf** [comment]
Until appveyor fixes this, it will be useful to print the rate limit info for `conda-forge-admin` as well. We are now printing the limit of `conda-forge-manager`

**Comment by isuruf** [comment]
@pelson, since you have access to `conda-forge-admin`, will you be able to add a github token to this repo so that we can print the limit of `conda-forge-admin`?

**Comment by isuruf** [comment]
This is not needed
