### ISSUE TITLE
Package Request: nltk-with-data

### ISSUE THREAD

**Issue by AbdealiJK** [conda-forge/staged-recipes#3615]
It would be really great if we can create a package like nltk-with-data. We already have nltk and making a new package which depends on it called "nltk-data" would be really useful.

This is extremely useful to keep a track of which data version is there and also makes it easier to install behind proxies and so on.

https://gist.github.com/danielfrg/d17ffffe0dc8ed56712a0470169ff546 is a recipe made by @danielfrg maybe we can build on top of that ?

**Comment by danielfrg** [comment]
I am maintaining that recipe here now: https://github.com/danielfrg/conda-recipes/tree/master/nltk-with-data. I have used it for exactly what you mention, proxies, spark clusters and other weird installs.

I have not pushed that one to conda-forge because i think its a little of a weird recipe mix. You can get it from my anaconda.org channel : `conda install -c danielfrg nltk-with-data` note that you have to remove `nltk` first.

Probably a pkg called just `nltk-data` is a better idea but since NLTK at the moment needs a (small) patch to read from a conda environment its not viable right now. I just need to get some time to make a proper PR to NLTK and then it should be easier.

**Comment by jakirkham** [comment]
Wonder if the @conda-forge/nltk contributors have any thoughts here.

**Comment by danielfrg** [comment]
This is actually going to be very easy soon, there is an [open PR](https://github.com/nltk/nltk/pull/1816#issuecomment-327201105) to make nltk read from `sys.prefix` this will allow is to have an `nltk-data` pkg that `nltk` can read from.

**Comment by AbdealiJK** [comment]
Now https://github.com/nltk/nltk/pull/1816 has been merged and has been released in the latest nltk version.
@danielfrg or @pmlandwehr or others - would you be interested in making the nltk-data package for conda-forge ?

**Comment by danielfrg** [comment]
Thanks for letting us know. I will do it soon :)

**Comment by AbdealiJK** [comment]
Closing this as https://github.com/conda-forge/staged-recipes/pull/4463 was merged.
