### ISSUE TITLE
Appveyor HTTPS error on 

### ISSUE THREAD

**Issue by nickp60** [conda-forge/staged-recipes#3809]
Sorry for creating another issue!   Could someone help me troubleshoot this build?
https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.16312

```
conda install --yes --quiet conda-build-all
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-32/repodata.json>
Elapsed: -
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(ReadTimeoutError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Read timed out.",),)

```

**Comment by jdblischak** [comment]
The key line is this one:

```
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

I'll restart the build for you on Appveyor.

**Comment by notestaff** [comment]
Could the Appveyor build script be changed to automatically retry in case of HTTP errors?  I'm seeing these often.  @conda-forge/core

**Comment by nickp60** [comment]
I see.  @jdblischak would you mind restarting this one too? I'ts only failing on one of the tests...
https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.16403

**Comment by nickp60** [comment]
@notestaff, Also, I'm very new to appveyor, but I came across this:
https://github.com/appveyor/ci/blob/master/scripts/appveyor-retry.cmd

could something like this be implemented?

**Comment by jdblischak** [comment]
> would you mind restarting this one too? I'ts only failing on one of the tests...

@nickp60 PR restarted.

Note that the fact that a few of the tests fail due to the HTTP error is not informative to whether your recipe is good to merge. Appveyor performs 6 builds: Python 2.7, 3.5, and 3.6 on x86 and x64 architectures. If your recipe builds on most of them, it is probably fine.

In my opinion, the main benefit of restarting a PR and getting it to pass is that it is easier for others to review and merge. Otherwise it has to be decided how likely it is that the particular package would be affected by the Python version or architecture prior to merging.

**Comment by jdblischak** [comment]
> Could the Appveyor build script be changed to automatically retry in case of HTTP errors? I'm seeing these often.

@notestaff Agreed. This does seem to be happening frequently. Thanks for opening PR https://github.com/conda-forge/staged-recipes/pull/3836 to attempt to fix this (based on the suggestion from @nickp60).

**Comment by nickp60** [comment]
@jdblischak thanks so much for restarting those:  the first time, 2 of the architectures failed, and this second time, only one did.  Fingers crossed!

and thanks @notestaff for making that PR happen!
