### ISSUE TITLE
Add recipe for cssmin

### ISSUE THREAD

**Issue by csadorf** [conda-forge/staged-recipes#3944]
It would be nice to have cssmin on conda-forge.

https://github.com/zacharyvoase/cssmin

**Comment by jenzopr** [comment]
Hi!
I had a quick look at the cssmin PyPI package. There is no license file within the source package on PyPI and I do not have hope that the maintainer will change this soon, as the git repo states that cssmin is no longer maintained.
In order to get the license file, we could use the tagged release(s) from github as source.
Is this a good workaround? I could proceed with writing the recipe in both cases.

**Comment by csadorf** [comment]
There is no explicit license stated in the pypi manifest as it seems either. I think it fair to assume that the software is licensed under the BSD license as stated in the repository.

I think that using the latest tagged release would be a reasonable approach. Is there anything I can help with?
