### ISSUE TITLE
Staged recipes not in `recipes` directory

### ISSUE THREAD

**Issue by synapticarbors** [conda-forge/staged-recipes#4584]
While reviewing a recipe (and subsequently merging it), I failed to notice that the recipe was in the top level directory rather than in `recipes`. Talking with @jakirkham it seems like this is a common problem. 

I suggested that perhaps the linter should be able to automatically catch this common error and wanted to raise the issue for further discussion here. 

@conda-forge/core

**Comment by jakirkham** [comment]
Generally the fix can go in one of three places (potentially in some combination of these). In staged-recipes CIs themselves, in `conda-smithy` (the CLI for the linter lives there), in `conda-forge-webservices` (this runs the linting bot). Would have a slight preference towards solving this in CIs at `staged-recipes` as the issue is localized here. Though could also see value in adding something to the bot (i.e. `conda-forge-webservices`) so that we spell out the problem to the user (instead of having them dig through CI logs). Either way `conda-smithy` itself feels like the wrong place for this as it has no real concept of `staged-recipes`. Other thoughts?

**Comment by CJ-Wright** [comment]
I'd rather not try to fish this out of the CI dump (unless we tried to make it super obvious, eg the error is done before any major output is accumulated).

**Comment by BastianZim** [comment]
Something like this?

https://github.com/conda-forge/staged-recipes/pull/21451

Haven't properly worked on the text yet. It's based on the linter we had in the docs. https://github.com/conda-forge/conda-forge.github.io/pull/1535

cc @beckermr @jakirkham
