### ISSUE TITLE
What is the workflow to submit a recipe to conda-forge?

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/staged-recipes#5]
@pelson I want to start packaging `geos` and `shapely` in the conda-forge channel.

Should I create a feedstock repo in the conda-forge organization or should I send the recipes here to staged-recipes?

**Comment by pelson** [comment]
> Should I create a feedstock repo in the conda-forge organization or should I send the recipes here to staged-recipes?

I'm still not certain at this point. I think, given anybody who wants to submit a feedstock would have to request a new repo, it makes sense to submit here, and we manually create the feedstock repos (using conda-smithy) once merged.

Obviously there are still some details to work out, and I've not really taken much time to do so recently - I'll start pulling on this thread more throughout October.

In the meantime, if you didn't have a [building mechanism in IOOS](https://github.com/ioos/conda-recipes), I'd recommend submitting a PR here, but since you do, it might make sense not to duplicate the recipe just yet - your call though.

**Comment by ocefpaf** [comment]
> it might make sense not to duplicate the recipe just yet - your call though.

My goal is to deprecate all the IOOS recipes I move to conda-forge to avoid duplication.  And then set a copy-script to copy the binaries from conda-forge to the IOOS channel.  I want to make conda-forge **the** canonical place for our recipes.

**Comment by pelson** [comment]
>  I want to make conda-forge the canonical place for our recipes.

:+1: - I wholeheartedly agree with that approach. Thankfully we are both in a good position at the moment with our anaconda channels, but the more we can share in terms of recipes (not just between us, but to the wider community) the better.

**Comment by ocefpaf** [comment]
See #6.

I will create the feedstocks later this week.

**Comment by jakirkham** [comment]
I am really excited about this. I'd love to contribute recipes here. In particular, I would like to start with a OpenBLAS backed copy of NumPy and SciPy. If you can tell me how you would like me to proceed, I will happily get started.

**Comment by pelson** [comment]
> In particular, I would like to start with a OpenBLAS backed copy of NumPy and SciPy. If you can tell me how you would like me to proceed, I will happily get started.

I think for those particular cases, it might make sense to go straight for a full feedstock repository for each recipe - that should allow you full control of the build matrix, otherwise it is easy to get bogged down trying to fix OSX, Linux and Windows permutations for all of the Python versions. In terms of getting those feedstocks set up, it isn't too challenging, but it does require a number of manual steps which one of the conda-forge admins need to run through (part of conda-smithy is to automate this process entirely, so that it is effectively an instantaneous step to create a new feedstock repo - alas, that isn't quite complete yet).

Next steps depend on your level of excitement - if you want to get your teeth into this in the next few days, it might be worth trying to submit a PR to staged-recipes in the full knowledge that it will become a standalone feedstock in the near future. Alternatively, if you can wait a week or so, I'll try to improve the automation process, and use this as the kick to get me to finish conda-smithy :wink:

**Comment by jakirkham** [comment]
Sorry I dropped off the map for a bit. I'd be interested in trying the automated process when you are ready.

**Comment by jakirkham** [comment]
@pelson, any word? Still interested in helping.

**Comment by pelson** [comment]
@jakirkham - I've updated https://conda-forge.github.io/ a little bit. There is some information in there about contributing.

**Comment by jakirkham** [comment]
Thanks @pelson. It is looking pretty polished.

So, my main interest is still getting working a working copy of NumPy and SciPy with OpenBLAS going. It looks like this still does not exist. How do you want me to create the feedstock? I imagine I will need a fair bit of guidance as I am unfamiliar with the process here.

**Comment by ajgpitch** [comment]
It is not clear from reading this thread what the workflow is. I am trying to follow the instructions on:
https://github.com/conda-forge/conda-smithy
It seems that its necessary to populate the feedstock folder in some way first. I tried adding a meta.yaml, but I still have issues on Step 1 (recipe folder being created recursively).
Should I just add my meta.yaml to 'recipes' or 'ready_recipes' here?

> I've updated https://conda-forge.github.io/ a little bit. There is some information in there about contributing<
The section on contributing could be more clear on how add a new feedstock

**Comment by jakirkham** [comment]
Not totally sure how confused you are, @ajgpitch, or exactly on what, but this may help. Also, please correct me if I say something wrong @pelson.

At the bottom of the page there is a selection menu for what to do (admittedly this could be a bit clearer), from that you choose what it is you want to do.

<img width="1554" alt="screen shot 2016-02-23 at 0 29 39" src="https://cloud.githubusercontent.com/assets/3019665/13242676/38c04158-d9c5-11e5-8415-20527e5a1ad2.png">

When selecting add, it points us to the [staged-recipes]( https://github.com/conda-forge/staged-recipes ), which we need to fork.

<img width="1554" alt="screen shot 2016-02-23 at 0 36 36" src="https://cloud.githubusercontent.com/assets/3019665/13242694/93788038-d9c5-11e5-8327-73a6352b8f14.png">

I think the idea is you need a proper recipe folder with these contents ( http://conda.pydata.org/docs/building/recipe.html#conda-recipe-files-overview ), which then goes in the folder called "recipes" in your fork. Here is an example with [`prompt_toolkit`]( https://github.com/conda-forge/staged-recipes/tree/e06c0c36575a963f2a877108e9d71a891c7615f6/recipes/prompt_toolkit ). Then you PR this change back to the one here. Once the PR gets accepted there is some magic that happens behind the scenes and then, if all goes well, packages are built and uploaded to the [conda-forge]( https://anaconda.org/conda-forge ) channel.

**Comment by ajgpitch** [comment]
Thank you so much @jakirkham . Yes, it was the little selection arrow I was missing. All makes perfect sense now. I had already made a fork of staged-recipes, I was just unclear of what to do from there.

Probably goes without saying that I am new to this recipe thing, not having done a conda-build. So thanks for the link on that too.

Pretty sure I should be able to get something working now.

**Comment by pelson** [comment]
Thanks for the summary @jakirkham.

> Yes, it was the little selection arrow I was missing.

You're not the only one. Clearly my career in UI design isn't going to take off :smile: 
I'd be thrilled if somebody wanted to submit a design PR to https://github.com/conda-forge/conda-forge.github.io. :+1:

**Comment by jakirkham** [comment]
> Clearly my career in UI design isn't going to take off

Well, it is still a nicer site than I would have designed. ;)

Maybe moving the list widget to the end of the sentence might help. Also, the widget could get some background color like white or something to make it stick out against the background. Just my two cents.

**Comment by JanSchulz** [comment]
Why not make each question a headline and add the answer below the headline? Like

```
I like to...
* _Add a package_ [Links to the section below]
* _Report a bug_

# Add a package

... text ...

# Report a bug

... text ...
```

**Comment by pelson** [comment]
I think the original question has now been answered (that and a few others beside). I'm going to close this issue.

@JanSchulz - I'm not averse to the changes proposed, though they would need to be done in a way that was consistent with the styling of the conda-forge.github.io homepage (i.e. not extremely verbose). Happy to take PRs at https://github.com/conda-forge/conda-forge.github.io

**Comment by JanSchulz** [comment]
See https://github.com/conda-forge/conda-forge.github.io/pull/38 

Not sure if I got that right, I've no clue what all the divs mean...
