### ISSUE TITLE
Package auto-sklearn

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#5656]
Would be great to have a package for [`auto-sklearn`]( https://pypi.python.org/pypi/auto-sklearn ).

**Comment by Bergvca** [comment]
Some dependencies required:
  
- xgboost==0.7.post3
  - pynisher[version='>=0.4']
  - liac-arff
  - pyrfr[version='>=0.7,<0.8']
  - configspace[version='>=0.4.0,<0.5']
  - smac

**Comment by dhirschfeld** [comment]
Just poking about to see what's involved:

* https://github.com/automl/auto-sklearn/blame/master/requirements.txt
* https://github.com/conda-forge/liac-arff-feedstock
* https://github.com/conda-forge/configspace-feedstock
* https://pypi.org/project/pynisher/
* https://pypi.org/project/pyrfr/
* https://pypi.org/project/smac/

**Comment by dhirschfeld** [comment]
It turns out that a `pynisher` PR is already up on `staged-recipes` - https://github.com/conda-forge/staged-recipes/pull/13861

**Comment by BastianZim** [comment]
@dhirschfeld Yeah I've been adding some of the missing dependencies but there is a small question with pynisher that still needs to be resolved, otherwise everything should be good to go. 
On another note: Are you then going to add `auto-sklearn`? I've been adding some packages from here just to close some issues, not because I need them or necessarily want to be the maintainer, so if you want to take some of them over feel free to!

**Comment by BastianZim** [comment]
I've also started adding smac but that depends on pynisher and pyrfr.

**Comment by jakirkham** [comment]
Also we have [`configspace`]( https://github.com/conda-forge/configspace-feedstock )

cc @hadim

**Comment by dhirschfeld** [comment]
Thanks for the PRs @BastianZim!

I would like to get `auto-sklearn` on CF but am not sure I'll have the time in the immediate future. It's certainly on my TODO list though and now that you've done the hard work with the deps that's a bit more likely!

**Comment by BastianZim** [comment]
PR is at #14305
