### ISSUE TITLE
Travis is broken on master

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/staged-recipes#594]
```shell
Calculating the recipes which need to be turned into feedstocks.
Making feedstock for nilearn
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==0.10.0', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 228, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 101, in __call__
    generate_feedstock_content(feedstock_directory, args.recipe_directory, meta)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 32, in generate_feedstock_content
    configure_feedstock.main(target_directory)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 323, in main
    for key, value in file_config.items():
AttributeError: 'list' object has no attribute 'items'
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 94, in <module>
    '--feedstock-directory', feedstock_dir])
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'init', '/Users/travis/build/conda-forge/staged-recipes/recipes/nilearn', '--feedstock-directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmp1xgk4lu5__feedstocks/nilearn-feedstock']' returned non-zero exit status 1
```

**Comment by jakirkham** [comment]
It's a bug in `conda-smithy`.

**Comment by jakirkham** [comment]
At least that's what it looks like to me.

**Comment by ericdill** [comment]
Indeed. I've almost got it sorted.

**Comment by ericdill** [comment]
conda-forge/conda-smithy#164 fixes the problem locally for me.

**Comment by ericdill** [comment]
travis is getting a pretty serious backlog due to this bug. Could one of the conda-smithy admins have a look at that PR ASAP?

**Comment by jakirkham** [comment]
Unfortunately I am already pretty swamped. Maybe someone else can take a look.

**Comment by ericdill** [comment]
Alright. Hopefully someone else can give it a look then.  This bug is causing any merged PRs to not have their recipes moved out of staged-recipes/recipes.  Now those recipes  get built *any* time the CI's run (glueviz, nilearn and supervisor for now) in addition to the recipes that are actually being tested and added in new PRs.

**Comment by jakirkham** [comment]
> Alright. Hopefully someone else can give it a look then.

I'm sure @pelson will look in the morning (UK time). He has pretty good insight into these sorts of things.

> This bug is causing any merged PRs to not have their recipes moved out of staged-recipes/recipes.

Yes, like all services there are downtimes. As this is a community-based one that is in its early stages, patience is very important. Everyone here has day jobs that to varying extents do not involve this. That being said, I'm sure this will be resolved well within a day.

>  Now those recipes get built any time the CI's run (glueviz, nilearn and supervisor for now) in addition to the recipes that are actually being tested and added in new PRs.

Actually this is easily fixed. Simply merge your PR's branch with `master` and then `git rm -r` the recipes that need to go. After committing and pushing, I think you will find that everything builds fine in your PR without extra stuff.

**Comment by ericdill** [comment]
I'd like to apologize for the tone of my posts in this thread. I was feeling a
combination of guilty and anxious from my first attempt at using conda-forge
resulting in a number of very long builds (30-60 minutes) that served to back
up the queue for others trying to contribute recipes/packages. In an attempt to
reduce my anxiety from submitting a recipe that backed up the queue for others,
I thought I'd tackle this bug that was preventing recipes from being
transformed from staged-recipes/recipes/ into feedstocks and was dismayed to
find a few places where git blame showed code that I had written in
conda-smithy was in or near the stack trace that @ocefpaf listed.  Needless to say that
didn't help with the anxiety...  What you are seeing in this thread is me being
frantic about trying to solve a problem that I feel I had a part in creating
and not trying to be selfish about my builds not being executed quickly enough.
Though there is no way that you would know any of this since I neglected to
mention it.  

With that being said, you are totally right that 

> patience is very important

and that 

> Everyone here has day jobs that to varying extents do not involve this

and so you have my sincere apologies.

Also, very good point about just removing the recipes from master.

**Comment by pelson** [comment]
Should be fixed in v0.10.2.

**Comment by jakirkham** [comment]
Thanks @pelson. 😄

**Comment by pelson** [comment]
It actually turned out to need a v0.10.3. Thank goodness for quick releases :+1: :smile:
