### ISSUE TITLE
503 server error from repo.continuum.io: Back-end server is at capacity!

### ISSUE THREAD

**Issue by ericdill** [conda-forge/staged-recipes#686]
Is it possible to mitigate this in any way?

Error: HTTPError: 503 Server Error: Service Unavailable: Back-end server is at capacity for url: https://repo.continuum.io/pkgs/pro/noarch/repodata.json.bz2: https://repo.continuum.io/pkgs/pro/noarch/

Seeing this on [circle] (https://circleci.com/gh/conda-forge/staged-recipes/4201) and [maybe travis] (https://travis-ci.org/conda-forge/staged-recipes/jobs/133356853#L172)

**Comment by jakirkham** [comment]
@msarahan, adding you because of the capacity issues we are running into.

**Comment by pelson** [comment]
It has gone quiet here somewhat. This may also be a more general question suited for the conda-forge.github.io repo (feedstocks presumably had the same issue).

I'm going to close this issue, and suggest we reopen as we see the issue occur.

Thanks!

**Comment by jakirkham** [comment]
@jjhelmus and I were discussing in this issue ( https://github.com/conda-forge/staged-recipes/issues/610 ) that having a conda-forge version of miniconda and/or have a copy with our typical dev dependencies thrown in would probably help. This should significantly cutdown on many of these regular queries to the conda-forge channel. Though some of the CI skip stuff added should help this problem a bit too. In any event, this issue is a sign that we are having growing pains; even though, it is a bit stressful for all involved, I take it as a sign of success of our mission.
