### ISSUE TITLE
Package Request: dlib

### ISSUE THREAD

**Issue by AbdealiJK** [conda-forge/staged-recipes#688]
It would be nice to add dlib here too https://github.com/davisking/dlib

CC @patricksnape as menpo already has it - https://github.com/menpo/conda-dlib

**Comment by pelson** [comment]
Definitely a case of the more the merrier at conda-forge so I'm 👍  on having dlib. Since there is an issue open over at menpo to serve as a reminder to @patricksnape, I'm going to go ahead and close this issue.

Thanks for raising the awareness of dlib, and I'd be happy to help with reviewing of a staged-recipe PR.

Thanks!
