### ISSUE TITLE
Make SpaCy models available as conda installs.

### ISSUE THREAD

**Issue by JIVJGFJZKF** [conda-forge/staged-recipes#7728]
Make conda install models from SpaCy, similar to the pip installs listed on their site.  Models are available at [SpaCy Models](https://spacy.io/models/).  The preference of order would be (highest on top/#1):

1. English
2. German/French/Spanish
3. Portuguese/Italian/Dutch
4. Multi-Language

**Comment by sodre** [comment]
@JIVJGFJZKF, would you be able to create the PR's for Portuguese, Italian, Dutch and Multi-language? You can follow the same recipes that I did for German #7791 , French #7793  and Spanish #7792  as a basis. 

Feel free to add me as a co-maintainer in the new PRs

**Comment by honnibal** [comment]
We packaged the models as pip packages, but we haven't uploaded them to PyPi. I think they do sort of work as packages, but there are a few caveats to be aware of:

* Some of the models are fairly large (up to 1gb currently, future models could be even bigger)

* Compatibility is a bit different from semver, since spaCy is allowed to break compatibility with the pretrained models even on a minor version (we try not to break on patch versions, though). We handle the compatibility by having `spacy download` check a compatiblity table, which we keep here: https://github.com/explosion/spacy-models/blob/master/compatibility.json . If anyone's maintaining these, please be very careful about compatibility: it's possible future versions of spaCy could make some change where the models load, but produce nonsense results, due to train/test skew after a code change.

* Normally when you install spaCy model packages, they create a symlink in the data directory. This lets shortcuts like `spacy.load('en')` work. We sort of hate this now, but we're stuck with it for backwards compatibility. These shortcut links won't work if you install via conda, which might confuse some people.

When I first saw these going up, my kneejerk reaction was to be a bit worried. It looked like a third-party mirror, which made me anxious about the data integrity. I see the data's being sourced from the Github releases though, which is cool --- I really like the way conda forge does things.

**Comment by JIVJGFJZKF** [comment]
> @JIVJGFJZKF, would you be able to create the PR's for Portuguese, Italian, Dutch and Multi-language? You can follow the same recipes that I did for German #7791 , French #7793 and Spanish #7792 as a basis.
> 
> Feel free to add me as a co-maintainer in the new PRs

@sodre I have completed the recipes for Portuguese #7917, Italian #7919, and Dutch #7920.  I built the multi-language package and did a pull request, it is #7940.  That should take care of all recipes....

**Comment by chrisburr** [comment]
I think they've all been merged so this can be closed?

If I'm missing something let me know and I'll re-open this issue.
