### ISSUE TITLE
Master is broken at the moment

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/staged-recipes#838]
@pelson not sure what is going on. The `scp` feedstock was created properly. So I will remove the recipe manually for now. Is that OK? (See https://travis-ci.org/conda-forge/staged-recipes/jobs/139270697)

```shell
CI support files regenerated. These need to be pushed to github!
[master 9b6f864] Re-render the feedstock after CI registration.
 2 files changed, 7 insertions(+), 7 deletions(-)
 rewrite conda-forge.yml (85%)
rm 'recipes/scp/meta.yaml'
HEAD detached at b193d4a
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)
	deleted:    recipes/scp/meta.yaml
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Miniconda3-latest-MacOSX-x86_64.sh
	bootstrap-obvious-ci-and-miniconda.py
Previous HEAD position was b193d4a... Merge pull request #830 from ocefpaf/add_scp
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
	Miniconda3-latest-MacOSX-x86_64.sh
	bootstrap-obvious-ci-and-miniconda.py
nothing added to commit but untracked files present
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 264, in <module>
    subprocess.check_call(['git', 'commit', '-m', msg])
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'commit', '-m', 'Removed recipe (scp) after converting into feedstock. [ci skip]']' returned non-zero exit status 1
```

**Comment by jakirkham** [comment]
It already removed it though and committed the change though ( https://github.com/conda-forge/staged-recipes/commit/baf5c2521aa2bf5f92d5518069cc86d8965b5cd0 ). 😕

**Comment by jakirkham** [comment]
Should add that if you look at the feedstock it has been re-rendered [many times]( https://github.com/conda-forge/scp-feedstock/commits/9b6f86463aac452f40c27cf88adf68e7b249b9bd ). Maybe the build got canceled and restarted a few times. Given how close to the end it would have to have been, I don't think this was done by someone intentionally. Could be some weird behavior on Travis CI's Linux container workers? While nothing has been reported, we have seen a significant slow down on them to. For instance, the feedstock/team update script has been queued since ~0600UTC.

**Comment by pelson** [comment]
Is this issue still active? It isn't clear to me what the error is here - particularly as the commits have been added to the scp-feedstock.

Very strange, but as @jakirkham says, looks like TravisCI was having a few issues yesterday.

**Comment by ocefpaf** [comment]
Nope. Travis-CI was very backlogged (~2days)
