### ISSUE TITLE
Conda forge recipe cookbook?

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/staged-recipes#843]
Perhaps this is low priority, but it might be handy to put together a guide from going from `conda skeleton` to a conda forge recipe. As far as I know, there's no good "Meta.yaml Cookbook" out there, and that seems important for the long term. Presumably this is really something that should be on Anaconda, but until that happens we could start assembling a FAQ in the staged-recipes wiki.

**Comment by ocefpaf** [comment]
> Perhaps this is low priority

Not really. We just don't have enough manpower to do it.

I have a PR trying to improve the examples. Your input there would be most welcomed!

https://github.com/conda-forge/staged-recipes/pull/667

**Comment by pelson** [comment]
@pmlandwehr - if you are in a position to contribute, we have the very beginning of docs at https://github.com/conda-forge/conda-forge.github.io. A guide to help users from conda-skeleton to conda-forge would be a healthy thing to add there. If you do give it a shot, keep it short and simple to start, and we can iterate quickly to build it into a valuable resource.

Since this isn't really an issue with staged-recipes, I'm going to go ahead and close the issue. I hope that doesn't indicate that what you have raised isn't an excellent idea - the docs you describe would be something we would love to have!

Thanks,
